### ISSUE TITLE
Implement __len__ to return how many sets are inside the SetTrie and in query result

### ISSUE THREAD

**Issue by ldeluigi** [BBVA/mercury-settrie#11]
https://docs.python.org/3/reference/datamodel.html#object.__len__

It should be implemented both in SetTrie (to know how many sets are there in a pythonic way) and in the Result iterator to efficiently check for empty/non empty result and so on

**Comment by sbasaldua** [comment]
Hi again,

I have started a new branch to keep track/implement all the open issues: https://github.com/BBVA/mercury-settrie/blob/features/towards_146/CHANGELOG.md

I will start with this one. It requires just a minor interface function to connect the C++ property that already contains the length with the Python object.

**Comment by sbasaldua** [comment]
Fixed in version 1.4.6
